### ISSUE TITLE
Usernames longer than 30 characters?

### ISSUE THREAD

**Issue by tekgirl77** [TeamMentor/TBot#3]
Using the email address as the username is our convention for other platforms & products, including TA. Some email addresses are easily over 30 characters and this limitation prevents consistently using the email address as the username.

**Comment by DinisCruz** [comment]
ok, and what is connection with TBot? :)

**Comment by tekgirl77** [comment]
Isn't Tbot the admin interface and user store?  :)  Or is tbot just a
component of the admin interface?

Salle Ingle
Support & Implementation Specialist, eLearning
[image: https://www.securityinnovation.com/_img/art/logo.png]

**Comment by DinisCruz** [comment]
You need to open that issue https://github.com/TeamMentor/master

**Comment by tekgirl77** [comment]
Done!  Issue submitted [here](https://github.com/TeamMentor/Master/issues/957)
